[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
argh = "0.1.13"
tar = "0.4.44"
sha2 = "0.10.9"
flate2 = { version = "1.1.2", default-features = false, features = ["zlib-rs"] }
hex = "0.4.3"

